content_version: 2
key: waiguan_yigui
name: 外观
views:
- key: base
  name: 基底
- key: chuanda
  name: 穿搭
regions:
- key: chuanda
  name: 穿搭方案
  type: func
  is_text: true
  is_clickable: true
- key: fangan_1
  name: 方案1
  type: func
  is_text: false
  is_clickable: true
  view: chuanda
- key: taoyong
  name: 套用方案
  type: func
  is_text: true
  is_clickable: true
  view: chuanda
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: yigui
  name: 衣柜
  type: func
  is_text: true
  is_clickable: true
